[osc]
# This is the port that RustyShock is listening to (EX: VRChat's send port) 
# Default: 9001 
listen_port = 7005

# This is the port that RustShock is sending on (EX: VRChat's listen port) 
# Default: 9000 
send_port = 9000

# This is the IP Address of the computer with the OSC Client on it (EX: VRChat) 
# Default: 127.0.0.1 (LocalHost)
ip_address = "127.0.0.1"

[OpenShock-Legacy]
# OpenShock Legacy's endpoint to issue commands to.
# Default: OpenShock.Local
api_endpoint = "OpenShock.Local"