    [osc]
    # This is the port that RustyShock is listening to (EX: VRChat's send port) 
    # Default: 9001 
    listen_port = 7005
    
    # This is the port that RustShock is sending on (EX: VRChat's listen port) 
    # Default: 9000 
    send_port = 9000
    
    # This is the IP Address of the computer with the OSC Client on it (EX: VRChat) 
    # Default: 127.0.0.1 (LocalHost)
    ip_address = "127.0.0.1"

    # This is the Prefix expected from OSC for Shocker touchpoints
    # Default: /avatar/parameters/
    touchpointPrefix = "/avatar/parameters/"

    [firmware]
    # The firmware your controller device is using
    # Options: legacy, openshock, pishock
    # Default: legacy (When OpenShock 1.0 is released, this will be changed)
    firmware = "legacy"
    # This is the endpoint used for your specific firmware
    # This option will be refactored once we know how the endpoints for each host works.
    # if unnecessary it'll be adjusted as an advanced option for user experience
    # Default: OpenShock.Local
    api_endpoint = "openshock.local"

    [logging]
    # This is the log level that RustyShock will use.
    # Default: Info
    # options: Off, Info, Debug, Error
    level = "Debug"
    