# Example: 
# [[touchpoints]]
# address = "tail"          # address is the OSC Touchpoint address defined on your avatar
# method = 1                # method is the permitted method to use the Shockers, 0 is disabled, 1 is shock+vibe, 2 is vibrate only
# intensity = 0.1           # Maximum intensity that can be sent
# duration = 300            # maximum duration that can be sent
# ids = [1234, 5678, 9098 , 7654] # IDs of your shockers in the firmware


[[touchpoints]]
address = "tail"
method = [1,2]
intensity = 1.0
duration = 300
ids = [3863,1234]

[[touchpoints]]
address = "NoseBoop"
method = [1]
intensity = 0.1
duration = 300
ids = [3863]

[[touchpoints]]
address = "HeadPat"
method = [1]
intensity = 0.1
duration = 300
ids = [3863]

[[touchpoints]]
address = "tail1"
method = [1,2]
intensity = 1.0
duration = 6000
ids = [3863,1234]

[[touchpoints]]
address = "tail2"
method = [1,2]
intensity = 1.0
duration = 6000
ids = [4567,8907]

[[touchpoints]]
address = "tail3"
method = [1,2]
intensity = 1.0
duration = 6000
ids = [3863,8765]